name: 申请友链
title: "友链申请 | 网站名称"
body:
  - type: input
    id: name
    attributes:
      label: 网站名称
    validations:
      required: true
  - type: input
    id: imgurl
    attributes:
      label: 头像 / Logo 地址
    validations:
      required: true
  - type: input
    id: desc
    attributes:
      label: 网站描述
    validations:
      required: true
  - type: input
    id: siteurl
    attributes:
      label: 网站地址
    validations:
      required: true
  - type: input
    id: tags
    attributes:
      label: 标签（英文逗号分隔）
    validations:
      required: true